### ISSUE TITLE
OSError: not supported for this image mode

### ISSUE THREAD

**Issue by geftactics** [geftactics/python-StarTSPImage#1]
img = PIL.ImageOps.invert(img) is resulting in the following...

```
Traceback (most recent call last):
  File "img.py", line 70, in <module>
    raster = StarTSPImage.imageToRaster(png)
  File "/usr/local/lib/python3.8/dist-packages/StarTSPImage/StarTSPImage.py", line 40, in imageToRaster
    return buildRaster(img)
  File "/usr/local/lib/python3.8/dist-packages/StarTSPImage/StarTSPImage.py", line 13, in buildRaster
    img = PIL.ImageOps.invert(img)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageOps.py", line 489, in invert
    return _lut(image, lut)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageOps.py", line 57, in _lut
    raise OSError("not supported for this image mode")
OSError: not supported for this image mode
```

**Comment by geftactics** [comment]
Fixed in `0.2.4`
